language: c

cache: ccache

compiler:
  - gcc
  - clang

git:
  depth: 1
  quiet: true

os:
  - linux

addons:
  apt:
    packages:
      - cython

before_install:
  - eval "${MATRIX_EVAL}"


before_script:
  - ./contrib/setup-btor2tools.sh
  - ./contrib/setup-cadical.sh
  - ./contrib/setup-lingeling.sh

script:
  - $CC --version
  - ./configure.sh "${BTOR_CONFIG}"
  - cd build
  - make -j2
  - bin/test

env:
  - BTOR_CONFIG=''
  - BTOR_CONFIG='-g'
  - BTOR_CONFIG='--python'

matrix:
  include:
    - os: osx
      compiler: clang
      env:
        -  MATRIX_EVAL="BTOR_CONFIG='-g'"

    - os: osx
      compiler: clang

    - os: osx
      compiler: clang
      env:
        -  MATRIX_EVAL="pip2 install cython && BTOR_CONFIG='--python'"

  fast_finish: true

#branches:
#  only:
#    - master
#
