language: c

cache: ccache

compiler:
  - gcc
  - clang

git:
  depth: 1
  quiet: true

os:
  - linux
  - osx

before_script:
  - ./contrib/setup-btor2tools.sh
  - ./contrib/setup-cadical.sh
  - ./contrib/setup-lingeling.sh
  - ./contrib/setup-picosat.sh

script:
  - ./configure-cmake.sh "${BTOR_CONFIG}"
  - cd cmake-build
  - make -j2
  - bin/test

env:
  - BTOR_CONFIG='-g'
  - BTOR_CONFIG=''
  - BTOR_CONFIG='--python'

matrix:
  fast_finish: true

#branches:
#  only:
#    - master
