name: ci

on: [push, pull_request]

jobs:
  ci:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        name: [
          ubuntu,
          ubuntu-clang,
          ubuntu-debug,
          ubuntu-debug-gmp,
          ubuntu-py2,
          ubuntu-py3,
          macos,
          macos-clang,
          macos-debug,
          macos-debug-gmp,
          #          macos-py2,
          macos-py3,
        ]

        include:
          - name: ubuntu
            os: ubuntu-latest

          - name: ubuntu-clang
            os: ubuntu-latest
            env: CC=clang CXX=clang++

          - name: ubuntu-debug
            os: ubuntu-latest
            config: -g

          - name: ubuntu-debug-gmp
            os: ubuntu-latest
            config: -g --gmp

          - name: ubuntu-py2
            os: ubuntu-latest
            config: --python --py2
            cython: true

          - name: ubuntu-py3
            os: ubuntu-latest
            config: --python --py3
            cython: true

          - name: macos
            os: macos-latest

          - name: macos-clang
            os: macos-latest
            env: CC=clang CXX=clang++

          - name: macos-debug
            os: macos-latest
            config: -g

          - name: macos-debug-gmp
            os: macos-latest
            config: -g --gmp

#          - name: macos-py2
#            os: macos-latest
#            config: --python --py2
#            cython: true

          - name: macos-py3
            os: macos-latest
            config: --python --py3
            cython: true


    steps:
    - uses: actions/checkout@v1

#    - name: Restore ccache
#      id: restore-ccache
#      uses: actions/cache@v1
#      with:
#        path: ccache-dir
#        key: ${{ runner.os }}-ccache-${{ matrix.cache }}
#        restore-keys: ${{ runner.os }}-ccache-master-${{ matrix.cache }}

    - name: Restore Dependencies
      id: restore-deps
      uses: actions/cache@v1
      with:
        path: deps
        key: ${{ runner.os }}-deps-${{ hashFiles('contrib/setup-**.sh') }}

#    - name: Create ccache directory
#      if: steps.restore-ccache.outputs.cache-hit != 'true'
#      run: mkdir ccache-dir
#
#    - name: Install ccache
#      if: runner.os == 'Linux'
#      run: sudo apt-get install ccache -y
#
#    - name: Install ccache
#      if: runner.os == 'macOS'
#      run: brew install ccache
#
#    - name: Configure ccache
#      run: |
#        ccache --set-config=cache_dir=${{ github.workspace }}/ccache-dir
#        ccache --set-config=compression=true
#        ccache --set-config=compression_level=6
#        ccache -M 1G
#        ccache -z

    - name: Install Cython (Linux)
      if: matrix.cython && runner.os == 'Linux'
      run: sudo pip install -U cython

    - name: Install Cython (macOS)
      if: matrix.cython && runner.os == 'macOS'
      run: sudo pip3 install cython

    - name: Setup dependencies
      if: steps.restore-deps.outputs.cache-hit != 'true'
      run: |
        ./contrib/setup-btor2tools.sh
        ./contrib/setup-cadical.sh
        ./contrib/setup-lingeling.sh
        ./contrib/setup-cms.sh

    - name: Configure Boolector
      run: ${{ matrix.env }} ./configure.sh ${{ matrix.config }}

    - name: Build Boolector
      run: make -j2
      working-directory: build

#    - name: ccache Statistics
#      run: ccache -s

    - name: Run CTest
      run: ctest -j2 --output-on-failure
      working-directory: build
